version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /mnt/docker/acme/default:/etc/nginx/certs
      - /mnt/docker/nginx/conf.d:/etc/nginx/conf.d
      - /mnt/docker/nginx/vhost.d:/etc/nginx/vhost.d:ro
    links:
      - adapter
  adapter:
    image: david510c/docker-nginx-omniauth-adapter
    build: ./adapter
    env_file:
      - auth.env
    restart: always
    network_mode: bridge
